version: "3.8"

services:
  mafia-server:
    container_name: mafia-server
    image: sjw7324/mafia-server:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shared_network:
    external: true
