version: "3.8"

services:
  mafia-server:
    container_name: mafia-server
    image: sjw7324/mafia-server:latest
    ports:
      - "4000:4000"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
